### ISSUE TITLE
Is there a module for javac

### ISSUE THREAD

**Issue by Kreijstal** [jtulach/dew#3]
if I want to just compile java to javascript, how would I go about it?

**Comment by jtulach** [comment]
Thanks for your interest in bck2brwsr!

Please take a look at https://github.com/jtulach/dew/#readme - as part of
the website being generated also Javac is compiled. Good luck.
-jt

po 25. 3. 2019 v 17:01 odesílatel Kreijstal <notifications@github.com>
napsal:

**Comment by jtulach** [comment]
The modules for javac are `javacapi` and `javacimpl`. They are simple wrappers around
```
<dependency>
  <groupId>org.netbeans.external</groupId>
  <artifactId>nb-javac-api</artifactId>
</dependency>
```
and `nb-javac-impl` coming from NetBeans Maven repository. The actual sources are taken from [Hg nbjavac](http://hg.netbeans.org/main/nb-javac/) repository.

Is that what you were asking?
